version: '3.7'

services:
  mysql:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'lms'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - "3306:3306"
    restart: always
    networks:
      - mysql
    volumes:
      - ./my-sql-data:/var/lib/mysql

  librarymanagementsystem:
    image: library-management-system-img
    container_name: library-management-system-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app
      - mysql
    depends_on:
      - mysql

## Network Config
networks:
  mysql:
    driver: bridge
  app:
    driver: bridge