name: Github Actions Build Maven Project


on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Step 3 - Have Github Actions Build Maven Project
        run: mvn -B package --file pom.xml
        
      - name: Step 4 - List the current directory
        run: ls -a
        
      - name: Step 5 - What is in the target folder?
        run: |
          cd target
          ls -a
